CREATE DATABASE [CourseDiaryDB];

CREATE TABLE [Trainers](
	[Id] INT IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(255) NOT NULL,
	[Surname] VARCHAR(255) NOT NULL,
	[Email] VARCHAR(255) UNIQUE,
	[Password] VARCHAR(255) CHECK (LEN(Password)>=6),
	[DateOfBirth] DATE NOT NULL
);